version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: raw_customers
      - name: raw_geolocation
      - name: raw_order_items
      - name: raw_order_payments
      - name: raw_order_reviews
      - name: raw_orders
      - name: raw_products
      - name: raw_sellers
      - name: raw_category_translation